INSERT INTO authors (id, name) VALUES
(1, 'F. Scott Fitzgerald'),
(2, 'George Orwell'),
(3, 'Harper Lee'),
(4, 'Herman Melville'),
(5, 'J.D. Salinger'),
(6, 'Aldous Huxley'),
(7, 'J.R.R. Tolkien'),
(8, 'Ray Bradbury'),
(9, 'Fyodor Dostoevsky'),
(10, 'Homer'),
(11, 'Jane Austen'),
(12, 'Dante Alighieri'),
(13, 'Emily Brontë'),
(14, 'Mary Shelley'),
(15, 'Oscar Wilde'),
(16, 'Charlotte Brontë'),
(17, 'Bram Stoker'),
(18, 'Victor Hugo'),
(19, 'Miguel de Cervantes'),
(20, 'Leo Tolstoy'),
(21, 'Alexandre Dumas'),
(22, 'Nathaniel Hawthorne'),
(23, 'Mark Twain'),
(24, 'Charles Dickens'),
(25, 'Ernest Hemingway'),
(26, 'Gabriel García Márquez'),
(27, 'Gustave Flaubert'),
(28, 'Kurt Vonnegut'),
(29, 'Toni Morrison'),
(30, 'William Faulkner'),
(31, 'Joseph Conrad'),
(32, 'Vladimir Nabokov'),
(33, 'James Joyce'),
(34, 'Albert Camus'),
(35, 'Joseph Heller'),
(36, 'Cormac McCarthy'),
(37, 'John Steinbeck'),
(38, 'Jack Kerouac'),
(39, 'David Foster Wallace'),
(40, 'Don DeLillo'),
(41, 'Patrick Rothfuss'),
(42, 'Scott Lynch'),
(43, 'Neil Gaiman'),
(44, 'Mark Z. Danielewski'),
(45, 'Haruki Murakami');