INSERT INTO books (id, title, author_id, genre_id, description) VALUES
(1, 'The Great Gatsby', 1, 1, 'A tragic story of love and ambition set in the Roaring Twenties.'),
(2, '1984', 2, 2, 'A dystopian vision of totalitarian surveillance and mind control.'),
(3, 'To Kill a Mockingbird', 3, 1, 'A young girl confronts racial injustice in the American South.'),
(4, 'Moby-Dick', 4, 10, 'Captain Ahab seeks revenge on the great white whale in an epic sea adventure.'),
(5, 'The Catcher in the Rye', 5, 1, 'A disenchanted teen navigates alienation and identity in post-war America.'),
(6, 'Brave New World', 6, 2, 'A futuristic world of engineered happiness questions individuality.'),
(7, 'The Fellowship of the Ring', 7, 3, 'A band of heroes begins a quest to destroy a powerful ring.'),
(8, 'Fahrenheit 451', 8, 2, 'In a future where books are banned, one fireman questions the system.'),
(9, 'Crime and Punishment', 9, 5, 'A tormented man grapples with guilt and morality after committing murder.'),
(10, 'The Odyssey', 10, 10, 'Odysseus faces monsters and gods on his long journey home.'),
(11, 'Pride and Prejudice', 11, 1, 'Love and social class collide in this romantic classic.'),
(12, 'The Divine Comedy', 12, 5, 'An epic journey through Hell, Purgatory, and Paradise.'),
(13, 'Wuthering Heights', 13, 9, 'A haunting tale of love and revenge on the Yorkshire moors.'),
(14, 'Frankenstein', 14, 9, 'A scientist creates life and faces the monstrous consequences.'),
(15, 'The Picture of Dorian Gray', 15, 9, 'A man’s portrait bears the burden of his immoral choices.'),
(16, 'Jane Eyre', 16, 1, 'An orphan rises to independence and love amid hardship.'),
(17, 'Dracula', 17, 9, 'A vampire from Transylvania invades Victorian England.'),
(18, 'Les Misérables', 18, 4, 'A former convict seeks redemption during revolutionary France.'),
(19, 'Don Quixote', 19, 10, 'A deluded knight and his squire embark on absurd adventures.'),
(20, 'War and Peace', 20, 4, 'Nobility and peasants endure love and war in Napoleonic Russia.'),
(21, 'The Count of Monte Cristo', 21, 10, 'A man wrongfully imprisoned seeks elaborate revenge.'),
(22, 'The Scarlet Letter', 22, 1, 'A woman bears a child out of wedlock and is publicly shamed.'),
(23, 'Adventures of Huckleberry Finn', 23, 10, 'A boy and a runaway slave journey down the Mississippi River.'),
(24, 'Great Expectations', 24, 1, 'An orphan navigates class, love, and fortune in Victorian England.'),
(25, 'The Old Man and the Sea', 25, 1, 'An old fisherman struggles with a giant marlin in the Gulf Stream.'),
(26, 'One Hundred Years of Solitude', 26, 6, 'The rise and fall of a magical family in a mythical town.'),
(27, 'Madame Bovary', 27, 1, 'A woman’s pursuit of passion leads to disillusionment.'),
(28, 'Slaughterhouse-Five', 28, 2, 'A WWII soldier becomes unstuck in time amid horror and absurdity.'),
(29, 'Beloved', 29, 5, 'A former slave is haunted by the ghost of her dead child.'),
(30, 'The Sound and the Fury', 30, 7, 'A Southern family’s decline told in fragmented voices.'),
(31, 'Heart of Darkness', 31, 5, 'A voyage into the African Congo reveals human depravity.'),
(32, 'Lolita', 32, 1, 'A man’s obsession with a young girl leads to moral ruin.'),
(33, 'Ulysses', 33, 7, 'A modern retelling of The Odyssey through a day in Dublin.'),
(34, 'The Stranger', 34, 5, 'An indifferent man commits murder and faces absurd justice.'),
(35, 'Catch-22', 35, 8, 'A WWII pilot trapped in paradoxical bureaucracy tries to stay sane.'),
(36, 'The Road', 36, 3, 'A father and son struggle to survive in a post-apocalyptic world.'),
(37, 'The Grapes of Wrath', 37, 4, 'A family migrates west during the Great Depression.'),
(38, 'On the Road', 38, 8, 'Free-spirited youths travel across postwar America in search of meaning.'),
(39, 'Infinite Jest', 39, 8, 'A complex satire about addiction, tennis, and entertainment.'),
(40, 'White Noise', 40, 8, 'A professor faces fear of death in a media-saturated world.'),
(41, 'The Name of the Wind', 41, 3, 'A gifted young man recounts his journey to becoming a legend.'),
(42, 'The Lies of Locke Lamora', 42, 3, 'A con artist leads a crew of thieves in a Venetian fantasy city.'),
(43, 'American Gods', 43, 3, 'Old gods battle new as myth and reality collide across America.'),
(44, 'House of Leaves', 44, 8, 'A family’s house defies physics and spirals into madness.'),
(45, 'Kafka on the Shore', 45, 6, 'Two storylines blur dream and reality in metaphysical Japan.'),
(46, 'Norwegian Wood', 45, 5, 'A man remembers love and loss in 1960s Tokyo.'),
(47, 'Hard-Boiled Wonderland and the End of the World', 45, 2, 'Two parallel worlds reveal a surreal quest for identity.'),
(48, 'Colorless Tsukuru Tazaki and His Years of Pilgrimage', 45, 1, 'A man revisits his past to uncover the reason for abandonment.'),
(49, 'The Wind-Up Bird Chronicle', 45, 6, 'A Tokyo man descends into a metaphysical mystery to find his wife.'),
(50, '1Q84', 45, 2, 'Two people navigate an alternate reality controlled by mysterious forces.');
